### PR TITLE
 Add modifier key properties to return value

### PR DESCRIPTION
**Pull request by TobiasSchaffner**
Add properties for the modifier keys shift, ctrl, alt and cmd (also called meta).

### CODE REVIEW

**Comment by fresheneesz** [comment]
Hmm, theres several problems with the code you're suggesting:

1. This is a breaking change.
2. This makes it harder or more error prone to handle simple keys. IE, if you checked if the key was "a", you'd no longer be handling the "a" case if the meta key is currently being pressed. 
3. It isn't consistent for other modifier keys, like shift and alt. The method of attaching a string onto the front of the key does not scale well for multiple modifier keys. What order do you use? "shift alt x" or "alt shift x"? These are things we shouldn't require the programmer to remember or think about. 
4. There's also already a way to handle this, which is to use keydown and keyup, and keep track of what key is pressed.

On point 4, I would imagine a much better way of handling this would be to add modifier key properties to the value returned by `keysight`. That way you could do something like `if (ks.key == 'a' && ks.meta)`. That API wouldn't have any of the problems I listed above. What do you think about that addition?

**Comment by TobiasSchaffner** [comment]
> On point 4, I would imagine a much better way of handling this would be to add modifier key properties to the value returned by `keysight`. That way you could do something like `if (ks.key == 'a' && ks.meta)`. That API wouldn't have any of the problems I listed above. What do you think about that addition?

Yes that's much better. You could pass through all the available keyboard event instance properties this way. (ctrlKey, altKey, metaKey). The only issue I see is that you mixed up metaKey and ctrlKey regarding to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent. Rel: https://github.com/fresheneesz/keysight/issues/3

**Comment by fresheneesz** [comment]
Ah yeah. Well I'd welcome a PR that has an updated PR. And fixing the definition of meta would be acceptable too, probably with at least a minor version incriment. If you decide to do a PR, please include documentation.

**Comment by TobiasSchaffner** [comment]
@fresheneesz please review and rebuild the /dist parts. I have no idea how to build this package. Thanks!

**Comment by fresheneesz** [comment]
Thanks for writing this up. There are several failing tests, but I'll fix them post merge before I incrimend the minor version and publish it.

**Pull request merged**
